
import {Nunito} from 'next/font/google'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar"
import ClientOnly from "./components/ClientOnly"
//import Modal from "./components/modals/Modal"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Nunito({
  subsets:["latin"]
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${font.className}${geistSans.variable} ${geistMono.variable} antialiased`}
      ><ClientOnly>
        <Navbar />
      </ClientOnly>
        {children}
        
      </body>
    </html>
  );
}
